🌟 Exercise 1 : Array Creation and Manipulation

In [ ]:
import numpy as np

# 1D array with numbers from 0 to 9
arr = np.arange(10)

# Array display
print("1D NumPy array from 0 to 9:")
print(arr)

1D NumPy array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations

In [ ]:
import numpy as np

# Original list
my_list = [3.14, 2.17, 0, 1, 2]

# Conversion into NumPy array with type by default (float)
arr_float = np.array(my_list)

# Conversion into Int array (round to 0)
arr_int = arr_float.astype(int)

# Display
print("Original list:", my_list)
print("Converted to int NumPy array:")
print(arr_int)

Original list: [3.14, 2.17, 0, 1, 2]
Converted to int NumPy array:
[3 2 0 1 2]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays

In [ ]:
import numpy as np

# Array with values from 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

# 2D array display
print("3x3 NumPy array from 1 to 9:")
print(arr)

3x3 NumPy array from 1 to 9:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [4]:
import numpy as np

# CArray size (4, 5) with random numbers between 0 and 1
random_array = np.random.rand(4, 5)

# Array display
np.set_printoptions(precision=2, suppress=True)
print("2D array with random values:")
print(random_array)

2D array with random values:
[[0.87 0.47 0.16 0.49 0.2 ]
 [0.65 0.32 0.76 0.99 0.55]
 [0.65 0.57 0.26 0.57 0.6 ]
 [0.97 0.22 0.19 0.15 0.04]]


🌟 Exercise 5 : Indexing Arrays

In [ ]:
import numpy as np

# 2D Array
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

# End row selected (index 1 - start to 0)
second_row = array[1]

# Display
print("Second row of the array:")
print(second_row)

Second row of the array:
[20 21 22 23 24]


🌟 Exercise 6 : Reversing elements

In [7]:
import numpy as np

# Créer un tableau 1D de 0 à 9
arr = np.arange(10)
print("Original array:")
print(arr)

# Inverser l'ordre des éléments
reversed_arr = arr[::-1]
print("\nReversed array:")
print(reversed_arr)

Original array:
[0 1 2 3 4 5 6 7 8 9]

Reversed array:
[9 8 7 6 5 4 3 2 1 0]


🌟 Exercise 7 : Identity Matrix

In [8]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs

In [ ]:
import numpy as np

# 1D array example
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#  Sum and mean
sum_result = np.sum(arr)
average_result = np.mean(arr)

# Results
print(f"Sum: {sum_result}, Average: {average_result}")

Sum: 55, Average: 5.5


🌟 Exercise 9 : Create Array and Change its Structure

In [ ]:
import numpy as np

# 1 : Créer un tableau 1D array elements from 1 to 20

arr = np.arange(1, 21)  

# 2 : Resizing in matrice 4x5
matrix = arr.reshape(4, 5)

# Afficher le résultat
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values

In [11]:
import numpy as np

# Création d'un tableau exemple
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extraction des nombres impairs
odd_numbers = arr[arr % 2 != 0]

# Affichage du résultat
print(odd_numbers)

[1 3 5 7 9]
